# Data Encoding
Nominal/OHE Encoding

Label and Ordinal Encoding

Target Guided Ordinal Encoding

### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [57]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [58]:
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [59]:
df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [60]:
##create an instance of Onehotencoder

encoder = OneHotEncoder()

In [61]:
# Perform fit transform

encoded = encoder.fit_transform(df[['color']])

In [62]:
encoded

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [63]:
# As we can see we have got the sparse matrix i.e. matrix containing 0 and 1

# To get the matrix

encoded = encoder.fit_transform(df[['color']]).toarray()

In [64]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [65]:
# So here we have sort according to ascending order. So blue is first then green then red

In [66]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [67]:
encoder_df

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [68]:
# 'color': ['red', 'blue', 'green', 'green', 'red', 'blue']

# so for this dataset at first row for red there is 1 then blue so blue is 1 and so on. So, we have converted our categorical features to
# numerical which ML model understands

In [69]:
## for new data
encoder.transform([['blue']]).toarray()

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [70]:
pd.concat([df,encoder_df],axis=1)  # Both dataframes will concat columnwise

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

# For tips dataset

In [71]:
import seaborn as sns

df1 = sns.load_dataset('tips')

In [72]:
df1.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [73]:
# As we can see categorical features so will convert to numeric

In [74]:
encoded = encoder.fit_transform(df1[['sex','smoker','day','time']]).toarray()

In [75]:
encoded

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]])

In [76]:
# Now here our is tranform

In [77]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [78]:
encoder_df

sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
1           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
2           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
3           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
4           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
..          ...       ...        ...         ...      ...      ...      ...   
239         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
240         1.0       0.0        0.0         1.0      0.0      1.0      0.0   
241         0.0       1.0        0.0         1.0      0.0      1.0      0.0   
242         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
243         1.0       0.0        1.0         0.0      0.0      0.0      0.0   

     day_Thur  time_Dinner  time_Lunch  
0         0.0          1.0         0.0  
1         0.0          1.0         0.0  
2         0.0          1.0         0.0  
3         0.0          1.0         0.0  
4         0.0          1.0         0.0  
..        ...          ...         ...  
239       0.0          1.0         0.0  
240       0.0          1.0         0.0  
241       0.0          1.0         0.0  
242       0.0          1.0         0.0  
243       1.0          1.0         0.0  

[244 rows x 10 columns]

In [79]:
encoder_df.head()

sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0         1.0       0.0        1.0         0.0      0.0      0.0      1.0   
1         0.0       1.0        1.0         0.0      0.0      0.0      1.0   
2         0.0       1.0        1.0         0.0      0.0      0.0      1.0   
3         0.0       1.0        1.0         0.0      0.0      0.0      1.0   
4         1.0       0.0        1.0         0.0      0.0      0.0      1.0   

   day_Thur  time_Dinner  time_Lunch  
0       0.0          1.0         0.0  
1       0.0          1.0         0.0  
2       0.0          1.0         0.0  
3       0.0          1.0         0.0  
4       0.0          1.0         0.0

In [80]:
pd.concat([df1, encoder_df], axis=1).head()

total_bill   tip     sex smoker  day    time  size  sex_Female  sex_Male  \
0       16.99  1.01  Female     No  Sun  Dinner     2         1.0       0.0   
1       10.34  1.66    Male     No  Sun  Dinner     3         0.0       1.0   
2       21.01  3.50    Male     No  Sun  Dinner     3         0.0       1.0   
3       23.68  3.31    Male     No  Sun  Dinner     2         0.0       1.0   
4       24.59  3.61  Female     No  Sun  Dinner     4         1.0       0.0   

   smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  day_Thur  time_Dinner  \
0        1.0         0.0      0.0      0.0      1.0       0.0          1.0   
1        1.0         0.0      0.0      0.0      1.0       0.0          1.0   
2        1.0         0.0      0.0      0.0      1.0       0.0          1.0   
3        1.0         0.0      0.0      0.0      1.0       0.0          1.0   
4        1.0         0.0      0.0      0.0      1.0       0.0          1.0   

   time_Lunch  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0

### Label Encoding 
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [81]:
df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [82]:
from sklearn.preprocessing import LabelEncoder

In [83]:
lbl_encoder = LabelEncoder()

In [84]:
lbl_encoder.fit_transform(df[['color']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [85]:
lbl_encoder.transform(['red'])

array([2])

In [86]:
lbl_encoder.transform(['blue'])

array([0])

In [87]:
lbl_encoder.transform(['green'])

array([1])

### Ordinal Encoding
It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [88]:
from sklearn.preprocessing import OrdinalEncoder

In [90]:
# create a sample dataframe with an ordinal variable
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [104]:
df.head()

size
0   small
1  medium
2   large
3  medium
4   small

In [92]:
# Create an instance of OrdinalEncoder and perform fit_tranform

In [99]:
encoder = OrdinalEncoder(categories=[['small','medium','large']])  # It will assign 0 for small, 1 for medium, and 2 for large. As I have given sequence like that

In [105]:
encoded = encoder.fit_transform(df[['size']])

In [106]:
encoded

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [107]:
encoder.transform([['small']])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [108]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [109]:
df

city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [110]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [111]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [112]:
df['city_encoded']=df['city'].map(mean_price)

In [ ]:
df